### ISSUE TITLE
 5 days old new version is not working,butOld version before two month was working very fine.

### ISSUE THREAD

**Issue by webmumbai** [aaronnech/Who-Wants-to-Be-a-Millionaire#1]
5 days old new version is not working,butOld version before two month was working very fine.New version is not producing any error even.It is not working Latest FF or Latest Chomre either.

**Comment by aaronnech** [comment]
Hello! This was due to a partial commit to the questions.json file. The questions.json file needs to be well-formed and have at least one game with all games having exactly 15 questions. I uploaded the complete version. There are now two question set files.

**Comment by webmumbai** [comment]
Hi Aaron Nech,

Thanks for your prompt reply & sorry I can not reply in time.

I am attaching two zip file of  "Who wanted to be Millionaire"  HTML files.
for two new features.

1) nillionaireeenc - file for Javascript contains
*Encryption & Obfuscation of Q &A *

  I know  Encryption & Obfuscation can be reversed,but for playing game
that too is acedemic & not monetory few people will do that.

_2) HTML tag can be embed in Q & A so multimedia millionaire can be made._

If you incorporate this feature your game & code is really awesome.

_Thanks once again_

Jayesh Zatakia

**Comment by aaronnech** [comment]
Hey Jayesh,

I'm working on a version that uses a simple server written in NodeJS that will secure questions / answers. This one can be played by individuals. My only concern is that this is not as portable for a group setting and less tech-savvy people.

I can definitively encrypt and/or obfuscate the questions / code, but generally the way the game is played prevents the players from tampering with the game. (If this is to be carried out in a real life setting, with a projector for example).
